[package]
name = "url-shortener"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8" }
chrono = { version = "0.4.43", features = ["serde"] }
deadpool-postgres = "0.14.1"
dotenvy = "0.15.7"
hyper = { version = "1.8.1", features = ["full"] }
hyper-util = { version = "0.1.20", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.48", features = ["full"] }
tokio-postgres = { version = "0.7.16", features = [
    "with-serde_json-1",
    "with-chrono-0_4",
] }
tower-http = "0.6.8"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"

[dev-dependencies]
reqwest = { version = "0.13.1", features = ["json"] }
testcontainers = { version = "0.27.1", features = ["docker-compose"] }
testcontainers-modules = { version = "0.15.0", features = ["postgres"] }
