[package]
name = "url-shortener"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8" }
chrono = { version = "0.4.43", features = ["serde"]}
hyper = {version = "1.8.1", features = ["full"] }
hyper-util = {version = "0.1.20", features = ["full"]}
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.48", features = ["full"] }
tower-http = "0.6.8"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
